[project]
name = "citycoin"

[contracts.sip-010-trait]
path = "contracts/clarinet/sip-10-ft-standard.clar"
depends_on = []

[contracts.citycoin-lifecycle-trait]
path = "contracts/clarinet/citycoin-lifecycle-trait.clar"
depends_on = []

[contracts.citycoin-token]
path = "contracts/clarinet/citycoin-token.clar"
depends_on = ["sip-010-trait"]

[contracts.citycoin-vrf]
path = "contracts/clarinet/citycoin-vrf.clar"
depends_on = []

[contracts.citycoin]
path = "contracts/clarinet/citycoin.clar"
depends_on = ["citycoin-lifecycle-trait", "citycoin-token", "citycoin-vrf"]

[contracts.citycoin-core]
path = "contracts/clarinet/citycoin-core.clar"
depends_on = []

# contracts listed below are used only in test suite
[contracts.test-utils]
path = "contracts/clarinet/test-utils.clar"
depends_on = ["citycoin"]

[contracts.test-malicious]
path = "contracts/clarinet/test-malicious.clar"
depends_on = ["citycoin"]

[contracts.test-city-wallet]
path = "contracts/clarinet/test-city-wallet.clar"
depends_on = ["citycoin"]