# GitHub action to verify `clarinet check` runs against contract
# Uses a prepare script outlined in testing section of README

name: Test Contract

# Controls when the action will run.
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Setup Clarinet
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: clarinet --locked
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "15.x"
      - name: Run Clarinet Check
        run: npm run clarinet:check
